# TODO: rename to collector
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wes-lorawan-server
spec:
  selector:
    matchLabels:
      app: wes-lorawan-server
  template:
    metadata:
      labels:
        app: wes-lorawan-server
    spec:
      priorityClassName: wes-high-priority
      nodeSelector:
        resource.lorawan: "true"
      containers:
        - name: wes-lorawan-server
          image: 10.31.81.1:5000/local/lorawan:latest
          # TOOD: not sure if we need this, since we are mapping in /sys already
          securityContext:
            privileged: true
          resources:
            # TODO: analyze resource usage
            limits:
              cpu: 500m
              memory: 100Mi
            requests:
              cpu: 500m
              memory: 100Mi
          envFrom:
            - configMapRef:
                name: wes-identity
          env:
            - name: MODEL
              value: "RAK7248"
            - name: BAND
              value: "US_902_928"
            - name: GATEWAY_EUI
              value: "D2CE19FFFEC9D449"
            - name: SERVER_HOST
              value: "wes-chirpstack-gateway-bridge"
            - name: SERVER_PORT
              value: "1700"
          volumeMounts:
            - name: sys
              # TODO: see if we can figure out a way to do /host/sys and modify code for that path
              # TODO: narrow the scope to /sys/class/gpio to see if that works, to limit exposure
              mountPath: /sys
              mountPropagation: HostToContainer
              readOnly: false
          # TODO: liveness probe to ensure its working
          # livenessProbe:
          #   exec:
          #     command:
          #       - "/bin/sh"
          #       - "-c"
          #       - "gpspipe -n20 -w wes-gps-server | grep -q -m1 TPV"
          #   timeoutSeconds: 10
          #   initialDelaySeconds: 30
          #   periodSeconds: 30
          #   successThreshold: 1
          #   failureThreshold: 3
      volumes:
        - name: sys
          hostPath:
            path: /sys
