[general]
# debug=5, info=4, warning=3, error=2, fatal=1, panic=0
log_level=5

[postgresql]
dsn="postgres://chirpstack_as:chirpstack_as@wes-chirpstack-postgresql/chirpstack_as?sslmode=disable"

[redis]
servers=["wes-chirpstack-redis:6379"]

[application_server]
id="6d5db27e-4ce2-4b2b-b5d7-91f069397978"

[application_server.integration]
enabled=["amqp"]

[application_server.integration.amqp]
url="amqp://service:service@wes-rabbitmq:5672"

[application_server.api]
bind="0.0.0.0:8001"
public_host="http://wes-chirpstack-application-server:8001"

[application_server.external_api]
bind="0.0.0.0:8080"
jwt_secret="sPQT3pZfR191Y9lJP9CreqbThIvjGlR8YYMNmav9hkI="

[join_server]
bind="0.0.0.0:8003"
