[general]
# debug=5, info=4, warning=3, error=2, fatal=1, panic=0
log_level=5

[postgresql]
dsn="postgres://chirpstack_ns:chirpstack_ns@wes-chirpstack-postgresql/chirpstack_ns?sslmode=disable"

[redis]
servers=["wes-chirpstack-redis:6379"]

[network_server]
net_id="000000"

[network_server.band]
name="US915"

[network_server.network_settings]
enabled_uplink_channels=[8,9,10,11,12,13,14,15]
disable_adr=true

[network_server.api]
bind="0.0.0.0:8000"

[network_server.gateway.backend]
type="amqp"

[network_server.gateway.backend.mqtt]
# Fully disable the MQTT as we are using AMQP / RabbitMQ
server=""

[network_server.gateway.backend.amqp]
url="amqp://service:service@wes-rabbitmq:5672"

[join_server.default]
server="http://wes-chirpstack-application-server:8003"
