apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wes-chirpstack-redis-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      # TODO: can probably reduce this
      storage: 100Mi
