# TODO: put all these chirpstack stuff in a single yaml
apiVersion: v1
kind: Service
metadata:
  name: wes-chirpstack-redis
spec:
  selector:
    app: wes-chirpstack-redis
  ports:
    - name: reids
      port: 6379
      targetPort: 6379
