# TODO: put all these chirpstack stuff in a single yaml
apiVersion: v1
kind: Service
metadata:
  name: wes-chirpstack-postgresql
spec:
  selector:
    app: wes-chirpstack-postgresql
  ports:
    - name: postgresql
      port: 5432
      targetPort: 5432
